In [7]:
import ee
import geopandas as gpd
from geesat import geogee 
import geesat
from shapely.geometry import box
geesat.authenticate_gee()

In [ ]:
# Example of area of interest (AOI) in Germany
bbox = [9.84375   , 47.5172007 , 10.1953125 , 47.75409798]
# Create an Earth Engine geometry object for the AOI
aoi = ee.Geometry.Rectangle(bbox)
# if you have geopandas dataframe, you can convert it to an Earth Engine geometry object like this:
# gdf = gpd.read_file("path_to_your_shapefile.shp")
# aoi = geesat.gdf_to_ee(gdf)

### 1. Landsat dataset

- **Generate cloud-free monthly LST in degree**

In [30]:
lst = geogee.generate_landsat_lst(aoi, start_date='1990-01-01', end_date='1990-12-31')
# make monthly composite
monthly_lst = geogee.generate_monthly_composite(lst, aggregate_method='mean')
print(f"Number of images in the original collection: {lst.size().getInfo()}")
print(f"Number of images in the monthly composite collection: {monthly_lst.size().getInfo()}")

Number of images in the original collection: 31
Number of images in the monthly composite collection: 12

- **Generate cloud-free surface reflectance and vegetation-related indices**

In [27]:
# Calculate predefined Landsat indices from Landsat 8 and 9 data
landsat_indices = geogee.generate_landsat_indices(aoi=aoi, start_date='2020-01-01', end_date='2020-12-31')
print(landsat_indices.first().bandNames().getInfo())

['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'NDVI', 'LST', 'NDWI', 'TVX', 'VTI']

### 2. Generate cloud-free Sentinel-2 data

- **Generate cloud-free data**

In [32]:
sen2data = geogee.generate_sen2_cloud_mask(aoi, start_date='2020-01-01', end_date='2020-12-31', cloud_filter=50)
print(f"Number of images in the original Sentinel-2 collection: {sen2data.size().getInfo()}")

Number of images in the original Sentinel-2 collection: 34

- **Generate monthly cloud-free composite**

In [33]:
# make monthly composite
monthly_sen2data = geogee.generate_monthly_composite(sen2data, aggregate_method='median')
print(f"Number of images in the monthly composite Sentinel-2 collection: {monthly_sen2data.size().getInfo()}")

Number of images in the monthly composite Sentinel-2 collection: 12

- **Generate n-day cloud-free composite**

In [34]:
# make n-day composite 
composite = geogee.generate_nday_composite(sen2data, aggregate_method='median', n_days=16)
print(f"Number of images in the 16-day composite Sentinel-2 collection: {composite.size().getInfo()}")

Number of images in the 16-day composite Sentinel-2 collection: 22

### 3. Load Sentinel-1 data and generate vh/vv and RVI (Radar vegetation Index) indices

In [35]:
sen1data = ee.ImageCollection("COPERNICUS/S1_GRD").filterBounds(aoi).filterDate('2020-01-01', '2020-12-31')
sen1indices = geogee.generate_sentinel1_indices(sen1data)
print(f"Number of images in the Sentinel-1 indices collection: {sen1indices.size().getInfo()}")
print(f"Band names in the Sentinel-1 indices collection: {sen1indices.first().bandNames().getInfo()}")

Number of images in the Sentinel-1 indices collection: 287
Band names in the Sentinel-1 indices collection: ['VV', 'VH', 'RVI', 'VH_VV_Ratio']

# 4. Extract raster values by vector data

In [42]:
# create 30 random points within the AOI
points = ee.FeatureCollection.randomPoints(aoi, 30)
print(f"Number of random points created: {points.size().getInfo()}")
# Create 30 polygons around the points with a buffer of 500 meters
polygons = points.map(lambda point: point.buffer(500).bounds())
print(f"Number of random polygons created: {polygons.size().getInfo()}")

Number of random points created: 30
Number of random polygons created: 30

- **Extract raster values by points**

In [ ]:
# Example extract LST values at the random points
lst = geogee.generate_landsat_lst(aoi, start_date='2025-06-01', end_date='2025-10-31')

lst_df = geogee.extract_raster_values_by_points(points, col=lst, scale=30, to_gdf=True).drop(columns=["id"])
lst_df.head() # NANs means cloud-masked pixels or missing data.

         time        LST                   geometry
0  2025-06-08        NaN  POINT (10.17086 47.54006)
1  2025-06-15        NaN  POINT (10.17086 47.54006)
2  2025-06-16        NaN  POINT (10.17086 47.54006)
3  2025-06-23  25.504588  POINT (10.17086 47.54006)
4  2025-06-24  25.754103  POINT (10.17086 47.54006)

In [52]:
# Another example extract Sentinel-2 data
sen2data = geogee.generate_sen2_cloud_mask(aoi, start_date='2025-06-01', end_date='2025-10-31', cloud_filter=50)
sen2df = geogee.extract_raster_values_by_points(points, col=sen2data, scale=30, to_gdf=True).drop(columns=["id"])
sen2df.head() # NANs means cloud-masked pixels or missing data.

,time,B1,B2,B3,B4,B5,B6,B7,B8,B8A,B9,B11,B12,geometry
0,2025-06-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (10.17086 47.54006)
1,2025-06-09,285.0,299.0,482.0,324.0,755.0,1959.0,2328.0,2492.0,2636.0,3497.0,1325.0,731.0,POINT (10.17086 47.54006)
2,2025-06-14,259.0,249.0,518.0,384.0,963.0,2201.0,2683.0,2560.0,2855.0,3534.0,1415.0,756.0,POINT (10.17086 47.54006)
3,2025-06-19,309.0,312.0,534.0,352.0,914.0,2326.0,2830.0,2867.0,3036.0,4020.0,1510.0,856.0,POINT (10.17086 47.54006)
4,2025-07-19,493.0,443.0,583.0,443.0,834.0,1905.0,2475.0,2462.0,2775.0,3774.0,1393.0,802.0,POINT (10.17086 47.54006)

- **Extract raster values by polygons**

In [51]:
lst_df = geogee.extract_raster_values_by_polygons(
    col=lst,
    polygon=polygons,
    scale=30,
    aggregate_method='mean',
    to_gdf=True
)
lst_df.head() # NANs means cloud-masked pixels or missing data.

         date       mean                                           geometry
0  2025-06-08  15.041322  POLYGON ((10.13456 47.60497, 10.14782 47.60497...
1  2025-06-08  16.197495  POLYGON ((9.84804 47.52124, 9.86128 47.52124, ...
2  2025-06-08  12.360390  POLYGON ((9.90855 47.60263, 9.92181 47.60263, ...
3  2025-06-08        NaN  POLYGON ((10.16435 47.53548, 10.17759 47.53548...
4  2025-06-08   7.834538  POLYGON ((10.00117 47.72996, 10.01446 47.72996...

In [53]:
# Another example extract Sentinel-2 data
sen2data = geogee.generate_sen2_cloud_mask(aoi, start_date='2025-06-01', end_date='2025-10-31', cloud_filter=50)
sen2df = geogee.extract_raster_values_by_polygons(
    col=sen2data,
    polygon=polygons,
    scale=30,
    aggregate_method='mean',
    to_gdf=True
)
sen2df.head() # NANs means cloud-masked pixels or missing data.

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A,B9,date,geometry
0,342.602570,1899.573758,931.909584,391.105772,721.120486,469.069224,1211.122608,3219.429206,3810.475194,3895.112059,4135.027994,4164.973370,2025-06-06,"POLYGON ((10.13456 47.60497, 10.14782 47.60497..."
1,255.770821,1935.389545,963.616520,327.999848,684.324246,393.327922,1169.568718,3463.258388,4183.423607,4259.332171,4468.996457,4463.310245,2025-06-06,"POLYGON ((9.84804 47.52124, 9.86128 47.52124, ..."
2,177.208203,1304.543055,617.238587,222.222497,469.080382,287.484794,821.789023,2314.278346,2770.268837,2828.187359,2959.502787,2951.926287,2025-06-06,"POLYGON ((9.90855 47.60263, 9.92181 47.60263, ..."
3,456.793413,1769.650361,906.517441,489.492300,783.626827,569.504120,1233.350099,2923.667734,3440.829199,3522.490678,3722.195563,3691.792332,2025-06-06,"POLYGON ((10.16435 47.53548, 10.17759 47.53548..."
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-06-06,"POLYGON ((10.00117 47.72996, 10.01446 47.72996..."